common:
  run_label: "run_1_infer"
  accum_freq: 1
  accum_after_epoch: -1
  log_freq: 500
  auto_resume: true
  mixed_precision: true
  results_loc: "/Users/eky/Documents/_SKRIPSI/code/result/detection_coco/edgeformer-s"
dataset:
  root_train: "/Users/eky/Documents/_SKRIPSI/code/imgs_dec"
  root_val: "/Users/eky/Documents/_SKRIPSI/code/imgs_dec"
  name: "krsbi_ssd"
  category: "detection"
  train_batch_size0: 32
  val_batch_size0: 32
  eval_batch_size0: 1
  workers: 2
  persistent_workers: false
  pin_memory: true
sampler:
  name: "batch_sampler"
  bs:
    crop_size_width: 224
    crop_size_height: 224
loss:
  category: "detection"
  detection:
    name: "ssd_multibox_loss"
    ssd_multibox_loss:
      neg_pos_ratio: 3
optim:
  name: "adamw"
  weight_decay: 0.02
  no_decay_bn_filter_bias: false
  adamw:
    beta1: 0.9
    beta2: 0.999
scheduler:
  name: "cosine"
  is_iteration_based: false
  max_epochs: 20
  warmup_iterations: 500
  warmup_init_lr: 0.00009
  cosine:
    max_lr: 0.0009
    min_lr: 1.e-6
model:
  detection:
    name: "ssd"
    ssd:
      anchors_aspect_ratio: [ [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [ 2, 3 ], [2] ]
      output_strides: [ 16, 32, 64, 128, 256, -1 ]
      proj_channels: [512, 256, 256, 128, 128, 64]
      center_variance: 0.1
      size_variance: 0.2
      iou_threshold: 0.5
      nms_iou_threshold: 0.5
    # pretrained: "parcnet/pretrained_models/detection/unbalance/checkpoint_best_run1.pt"
    # pretrained: "parcnet/pretrained_models/detection/unbalance/checkpoint_ema_best_run1.pt"
    pretrained: "parcnet/pretrained_models/detection/balance/checkpoint_best_run2.pt"
    # pretrained: "parcnet/pretrained_models/detection/balance/checkpoint_best_run1.pt"
    # pretrained: "parcnet/pretrained_models/detection/balance/checkpoint_ema_best_run1.pt"
    n_classes: 4
    # pretrained: "parcnet/pretrained_models/detection/checkpoint_ema_avg.pt"
    # n_classes: 81
  classification:
    name: "edgeformer"
    classifier_dropout: 0.2
    pretrained: "parcnet/pretrained_models/classification/checkpoint_ema_avg.pt"
    edge:
      scale: "scale_s"
      mode: "outer_frame_v1"
      kernel: "gcc_ca"
      fusion: "concat"
      instance_kernel: "interpolation_bilinear"
      use_pe: True
    activation:
      name: "swish"
  # normalization:
  #   name: "sync_batch_norm"
  #   momentum: 0.1
  activation:
    name: "relu" # If specific activation function is not specified, this one will be used as a default
    inplace: false
  layer:
    global_pool: "mean"
    conv_init: "kaiming_normal"
    linear_init: "normal"
    conv_weight_std: false
ema:
  enable: True
  momentum: 0.0005
ddp:
  enable: True
  rank: 0
  world_size: -1
  dist_port: 30787
stats:
  name: [ "loss" ]
  checkpoint_metric: "loss"
  checkpoint_metric_max: false